### ISSUE TITLE
Example has typo

### ISSUE THREAD

**Issue by reykjavikingur** [jwagner/normalmap.js#1]
Thanks for making this. It's such an awesome feature. We're trying to set up the example right now and noticed that the name `normalMap` is not what is defined by default. I installed the dependency with Bower and included it in my HTML like this:

`<script type="text/javascript" src="/assets/vendor/js/normalmap.js"></script>`

Trying the example code with the name `normalMap` throws an error because `normalMap` is undefined. I noticed that `normalmap` is defined, though that's inconsistent with the option key `normalMap`. Can you provide more accurate examples?

**Comment by jwagner** [comment]
I fixed the name in the example in the README.

Could you please define:

> the option key normalMap

do you mean _normalmap_({**normalMap**: ...})?

I guess that is a bit weird, and as demonstrated by the example, I even confused myself with that. ;)

In practice I don't think it's worth breaking the API to fix this though and it could be argued that they do in fact refer to two different concepts. One is the library that happens to be called _normalmap_ while the other refers to a map of normals and is consistent with the other maps. :)

**Comment by reykjavikingur** [comment]
I agree that the API ought to stay the same. I'm merely referring to the example code itself. However you defined the API, regardless of the case of letters in the function names and option keys, I was mainly referring to the example code. I think it will be easier to try out your module if developers can copy and paste directly from the README.

**Comment by jwagner** [comment]
I completely agree with you. That is fixed now, so I'll close this issue. Thanks for letting me now.
